PICKUP_COMMON_ITEMS = [
    :POTION,
    :ANTIDOTE,
    :SUPERPOTION,
    :FULLHEAL,
    :HYPERPOTION,
    :SUNSTONE,
    :MOONSTONE,
    :HEARTSCALE,
    :FULLRESTORE,
    :PPUP,
    :MAXELIXIR
]
PICKUP_COMMON_ITEM_CHANCES = [30, 10, 10, 10, 10, 10, 10, 4, 4]

PICKUP_RARE_ITEMS = [
    :HYPERPOTION,
    :NUGGET,
    :KINGSROCK,
    :FULLRESTORE,
    :ETHER,
    :IRONBALL,
    :DESTINYKNOT,
    :ELIXIR,
    :DESTINYKNOT,
    :LEFTOVERS,
    :DESTINYKNOT
]
